### ISSUE TITLE
tensorflow v0.13.0 fails to compile while executing the "bash" command.

### ISSUE THREAD

**Issue by lukecashwell** [tensorflow/rust#210]
I am using Windows 10, and have downloaded all the proper libraries to my knowledge. I have done a ton of searching through google and I am unable to find a solution to this issue. Here is the log: 
```
  Compiling tensorflow-sys v0.16.0
error: failed to run custom build command for `tensorflow-sys v0.16.0`

Caused by:
  process didn't exit successfully: `C:\Users\<USER>\Desktop\PixelGame\target\debug\build\tensorflow-sys-34a07f4d54933726\build-script-build` (exit code: 101)
--- stdout
libtensorflow-sys/build.rs:175: output = "C:\\Users\\<USER>\\Desktop\\PixelGame\\target\\debug\\build\\tensorflow-sys-cfa4ae906321c9db\\out"
libtensorflow-sys/build.rs:177: source = "C:\\Users\\<USER>\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\tensorflow-sys-0.16.0\\target/source-v1.13.1"
libtensorflow-sys/build.rs:179: lib_dir = "C:\\Users\\<USER>\\Desktop\\PixelGame\\target\\debug\\build\\tensorflow-sys-cfa4ae906321c9db\\out\\lib-v1.13.1"
libtensorflow-sys/build.rs:183: Creating directory "C:\\Users\\<USER>\\Desktop\\PixelGame\\target\\debug\\build\\tensorflow-sys-cfa4ae906321c9db\\out\\lib-v1.13.1"
libtensorflow-sys/build.rs:187: framework_library_path = "C:\\Users\\<USER>\\Desktop\\PixelGame\\target\\debug\\build\\tensorflow-sys-cfa4ae906321c9db\\out\\lib-v1.13.1\\libtensorflow_framework.so"
libtensorflow-sys/build.rs:189: library_path = "C:\\Users\\<USER>\\Desktop\\PixelGame\\target\\debug\\build\\tensorflow-sys-cfa4ae906321c9db\\out\\lib-v1.13.1\\libtensorflow.so"
libtensorflow-sys/build.rs:275: Executing "bazel" "version"
libtensorflow-sys/build.rs:277: Command "bazel" "version" finished successfully
libtensorflow-sys/build.rs:200: framework_target_path = "tensorflow/libtensorflow_framework.so"
libtensorflow-sys/build.rs:202: target_path = "tensorflow/libtensorflow.so"
libtensorflow-sys/build.rs:259: Executing "bash" "-c" "yes \'\'|./configure"

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panicking.rs:198
   4: std::panicking::default_hook
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panicking.rs:212
   5: std::panicking::rust_panic_with_hook
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panicking.rs:475
   6: std::panicking::continue_panic_fmt
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panicking.rs:382
   7: std::panicking::rust_begin_panic
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panicking.rs:309
   8: core::panicking::panic_fmt
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libcore\panicking.rs:85
   9: core::result::unwrap_failed<std::io::error::Error>
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\src\libcore\macros.rs:18
  10: core::result::Result<std::process::ExitStatus, std::io::error::Error>::unwrap<std::process::ExitStatus,std::io::error::Error>
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\src\libcore\result.rs:800
  11: build_script_build::run<closure>
             at .\build.rs:260
  12: build_script_build::build_from_src
             at .\build.rs:218
  13: build_script_build::main
             at .\build.rs:59
  14: std::rt::lang_start::{{closure}}<()>
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\src\libstd\rt.rs:64
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\rt.rs:49
  16: std::panicking::try::do_call<closure,i32>
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panicking.rs:294
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libpanic_unwind\lib.rs:82
  18: std::panicking::try
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panicking.rs:273
  19: std::panic::catch_unwind
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\panic.rs:388
  20: std::rt::lang_start_internal
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\/src\libstd\rt.rs:48
  21: std::rt::lang_start<()>
             at /rustc/0dc9e9c10ca6dc78cba8b9f9b15038c977b10a77\src\libstd\rt.rs:64
  22: main
  23: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
```
Does anyone know why this might happen?

**Comment by adamcrume** [comment]
I don't have access to a Windows machine, so unfortunately this library hasn't been well-tested on Windows.  You might find some help in #149.
