### ISSUE TITLE
Can't build on bash windows

### ISSUE THREAD

**Issue by tyoc213** [tensorflow/rust#36]
Here is the output

```
$ cargo build -j 1
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.17
   Compiling pkg-config v0.3.8
   Compiling tensorflow-sys v0.5.0 (file:///mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys)
error: failed to run custom build command for `tensorflow-sys v0.5.0 (file:///mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys)`
process didn't exit successfully: `/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/build-script-build` (exit code: 101)
--- stdout
libtensorflow-sys/build.rs:31: output = "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out"
libtensorflow-sys/build.rs:33: source = "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0"
libtensorflow-sys/build.rs:35: lib_dir = "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out/lib-0.10.0"
libtensorflow-sys/build.rs:39: Creating directory "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out/lib-0.10.0"
libtensorflow-sys/build.rs:43: library_path = "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out/lib-0.10.0/libtensorflow_c.so"
libtensorflow-sys/build.rs:48: target_path = "tensorflow/libtensorflow_c.so"
libtensorflow-sys/build.rs:102: Executing "git" "clone" "--branch=v0.10.0" "--recursive" "https://github.com/tensorflow/tensorflow.git" "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0"
libtensorflow-sys/build.rs:106: Command "git" "clone" "--branch=v0.10.0" "--recursive" "https://github.com/tensorflow/tensorflow.git" "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0" finished successfully
libtensorflow-sys/build.rs:77: Checking build file "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0/tensorflow/BUILD"
libtensorflow-sys/build.rs:84: Patching build file "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0/tensorflow/BUILD"
libtensorflow-sys/build.rs:102: Executing "./configure"
No Google Cloud Platform support will be enabled for TensorFlow
No GPU support will be enabled for TensorFlow
Configuration finished
libtensorflow-sys/build.rs:106: Command "./configure" finished successfully
libtensorflow-sys/build.rs:102: Executing "bazel" "build" "--jobs=1" "--compilation_mode=opt" "tensorflow:libtensorflow_c.so"

--- stderr
Clonar en «/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0»...
Note: checking out 'c715c3102df1556fc0ce88fc987440a3c80e5380'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Checking out files: 100% (4084/4084), done.
Can't do inplace edit on tensorflow/core/platform/default/build_config.bzl: No existe el archivo o el directorio.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:788
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Here is the backtrace (even that is pretty clear)

```
--- stderr
Can't open tensorflow/core/platform/default/build_config.bzl: No existe el archivo o el directorio.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x7fe71b839739 - std::sys::backtrace::tracing::imp::write::hd4b54a4a2078cb15
   2:     0x7fe71b8403ec - std::panicking::default_hook::_{{closure}}::h51a5ee7ba6a9fcef
   3:     0x7fe71b83f6e9 - std::panicking::default_hook::hf823fce261e27590
   4:     0x7fe71b83fd28 - std::panicking::rust_panic_with_hook::h8d486474663979b9
   5:     0x7fe71b83fb82 - std::panicking::begin_panic::h72862f004a4942ab
   6:     0x7fe71b83faf0 - std::panicking::begin_panic_fmt::hdc424a357d9142e1
   7:     0x7fe71b83fa71 - rust_begin_unwind
   8:     0x7fe71b8762cf - core::panicking::panic_fmt::h6b06f78ae7f9dd57
   9:     0x7fe71b80fb9c - core::result::unwrap_failed::hca88b4a09ab2a5f1
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:29
  10:     0x7fe71b80c005 - _<core..result..Result<T, E>>::unwrap::h59f218bad74f813b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:726
  11:     0x7fe71b816545 - build_script_build::run::h1436e6466b486231
                        at /mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/build.rs:17
  12:     0x7fe71b815249 - build_script_build::main::h84db52058401dfc4
                        at /mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/build.rs:58
  13:     0x7fe71b847ed6 - __rust_maybe_catch_panic
  14:     0x7fe71b83ee62 - std::rt::lang_start::hca48e539ce72a288
  15:     0x7fe71b817603 - main
  16:     0x7fe71aa01f44 - __libc_start_main
  17:     0x7fe71b8072d8 - <unknown>
  18:                0x0 - <unknown>
```

-------------------------

Also would prefer the name of the repo be some like tensorflow-rust so when you clone with guthub app doesnt overwrite rust repo :).

**Comment by adamcrume** [comment]
Do you have Bazel installed?  If not, [install it](http://bazel.io/docs/install.html) and try again.

**Comment by tyoc213** [comment]
Well, I did see that I only made the first step, later I follow the other steps and at the end need to do a install missing (there where some missing dependencies but apt says in the troubleshoting on console what to call).

Then I'm getting this


`````
RUST_BACKTRACE=1 cargo build -j 1
   Compiling tensorflow-sys v0.5.0 (file:///mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys)
jilerror: failed to run custom build command for `tensorflow-sys v0.5.0 (file:///mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys)`
process didn't exit successfully: `/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/build-script-build` (exit code: 101)
--- stdout
libtensorflow-sys/build.rs:31: output = "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out"
libtensorflow-sys/build.rs:33: source = "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0"
libtensorflow-sys/build.rs:35: lib_dir = "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out/lib-0.10.0"
libtensorflow-sys/build.rs:37: Directory "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out/lib-0.10.0" already exists
libtensorflow-sys/build.rs:43: library_path = "/mnt/c/Users/tyoc/test/nada/rust/target/debug/build/tensorflow-sys-5a768d9e18f318a5/out/lib-0.10.0/libtensorflow_c.so"
libtensorflow-sys/build.rs:48: target_path = "tensorflow/libtensorflow_c.so"
libtensorflow-sys/build.rs:77: Checking build file "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0/tensorflow/BUILD"
libtensorflow-sys/build.rs:82: Build file "/mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/target/source-0.10.0/tensorflow/BUILD" already patched
libtensorflow-sys/build.rs:102: Executing "./configure"
No Google Cloud Platform support will be enabled for TensorFlow
No GPU support will be enabled for TensorFlow
Configuration finished
libtensorflow-sys/build.rs:106: Command "./configure" finished successfully
libtensorflow-sys/build.rs:102: Executing "bazel" "build" "--jobs=1" "--compilation_mode=opt" "tensorflow:libtensorflow_c.so"

--- stderr
Can't open tensorflow/core/platform/default/build_config.bzl: No existe el archivo o el directorio.
Killed non-responsive server process (pid=736)
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Error: couldn't connect to server at '/home/tyoc213/.cache/bazel/_bazel_tyoc213/5c3c0546f18c9d860ed2814f35e42dc9/server/server.socket' after 60 seconds.
thread 'main' panicked at 'failed to execute "bazel" "build" "--jobs=1" "--compilation_mode=opt" "tensorflow:libtensorflow_c.so"', tensorflow-sys/build.rs:104
stack backtrace:
   1:     0x7f1c46239739 - std::sys::backtrace::tracing::imp::write::hd4b54a4a2078cb15
   2:     0x7f1c462403ec - std::panicking::default_hook::_{{closure}}::h51a5ee7ba6a9fcef
   3:     0x7f1c4623f6e9 - std::panicking::default_hook::hf823fce261e27590
   4:     0x7f1c4623fd28 - std::panicking::rust_panic_with_hook::h8d486474663979b9
   5:     0x7f1c4623fb82 - std::panicking::begin_panic::h72862f004a4942ab
   6:     0x7f1c4623faf0 - std::panicking::begin_panic_fmt::hdc424a357d9142e1
   7:     0x7f1c4621669d - build_script_build::run::h1436e6466b486231
                        at /mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/build.rs:8
   8:     0x7f1c46215249 - build_script_build::main::h84db52058401dfc4
                        at /mnt/c/Users/tyoc/test/nada/rust/tensorflow-sys/build.rs:58
   9:     0x7f1c46247ed6 - __rust_maybe_catch_panic
  10:     0x7f1c4623ee62 - std::rt::lang_start::hca48e539ce72a288
  11:     0x7f1c46217603 - main
  12:     0x7f1c45401f44 - __libc_start_main
  13:     0x7f1c462072d8 - <unknown>
  14:                0x0 - <unknown>
```

**Comment by adamcrume** [comment]
This could potentially be a Bazel problem, since they do note that Windows support for Bazel is experimental, but I don't want to claim that quite yet.  Can you try checking out the `v0.10.0` tag of the main TensorFlow project (make sure to do a recursive checkout) and building that with:

    ./configure
    bazel "build" "--jobs=1" "--compilation_mode=opt" "tensorflow:libtensorflow_c.so"

If that fails, the problem is probably not with the Rust bindings.  If it succeeds, we have more debugging to do.

Also, can you verify that `YOUR_TENSORFLOW_RUST_CHECKOUT/tensorflow-sys/target/source-0.10.0/tensorflow/core/platform/default/build_config.bzl` exists?

**Comment by tyoc213** [comment]
Later I will do all the steps you give.

For the moment there is no build_config.bzl

![imagen](https://cloud.githubusercontent.com/assets/506234/20733875/7c83de54-b65b-11e6-9224-11c875b2d116.png)

**Comment by adamcrume** [comment]
That doesn't make any sense.  The file exists in that version of TensorFlow, and nothing should delete it.  When you try the manual steps above, can you verify that the file exists after every step, including the git checkout?

**Comment by tyoc213** [comment]
this rust repo still give the problem above, but cloning tensor flow for compiling makes this other issue...


```
$ ./configure
/mnt/c/Users/tyoc/try2/tensorflow /mnt/c/Users/tyoc/try2/tensorflow
Please specify the location of python. [Default is /usr/bin/python]:
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] N
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] N
No CUDA support will be enabled for TensorFlow
Configuration finished
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Error: couldn't connect to server at '/home/tyoc213/.cache/bazel/_bazel_tyoc213/5ef3858c322258c9680e37d1b106360b/server/server.socket' after 60 seconds.
tyoc213@DESKTOP-MOVDAB7:/mnt/c/Users/tyoc/try2/tensorflow$ find . -iname "build_config.bzl"
./tensorflow/core/platform/default/build_config.bzl
```

guess it is bas on windows doesnt work.

**Comment by tyoc213** [comment]
I also try adding only the crate as dependency as #37 and I get

```
$ cargo build
   Compiling tensorflow-sys v0.5.0
                                                                                      error: failed to run custom build command for `tensorflow-sys v0.5.0`
process didn't exit successfully: `/mnt/c/Users/tyoc/try2/lala/target/debug/build/tensorflow-sys-f5d6b3977d411f10/build-script-build` (exit code: 101)
--- stdout
libtensorflow-sys/build.rs:31: output = "/mnt/c/Users/tyoc/try2/lala/target/debug/build/tensorflow-sys-f5d6b3977d411f10/out"
libtensorflow-sys/build.rs:33: source = "/home/tyoc213/.cargo/registry/src/github.com-1ecc6299db9ec823/tensorflow-sys-0.5.0/target/source-0.10.0"
libtensorflow-sys/build.rs:35: lib_dir = "/mnt/c/Users/tyoc/try2/lala/target/debug/build/tensorflow-sys-f5d6b3977d411f10/out/lib-0.10.0"
libtensorflow-sys/build.rs:37: Directory "/mnt/c/Users/tyoc/try2/lala/target/debug/build/tensorflow-sys-f5d6b3977d411f10/out/lib-0.10.0" already exists
libtensorflow-sys/build.rs:43: library_path = "/mnt/c/Users/tyoc/try2/lala/target/debug/build/tensorflow-sys-f5d6b3977d411f10/out/lib-0.10.0/libtensorflow_c.so"
libtensorflow-sys/build.rs:48: target_path = "tensorflow/libtensorflow_c.so"
libtensorflow-sys/build.rs:77: Checking build file "/home/tyoc213/.cargo/registry/src/github.com-1ecc6299db9ec823/tensorflow-sys-0.5.0/target/source-0.10.0/tensorflow/BUILD"
libtensorflow-sys/build.rs:82: Build file "/home/tyoc213/.cargo/registry/src/github.com-1ecc6299db9ec823/tensorflow-sys-0.5.0/target/source-0.10.0/tensorflow/BUILD" already patched
libtensorflow-sys/build.rs:102: Executing "./configure"
No Google Cloud Platform support will be enabled for TensorFlow
No GPU support will be enabled for TensorFlow
Configuration finished
libtensorflow-sys/build.rs:106: Command "./configure" finished successfully
libtensorflow-sys/build.rs:102: Executing "bazel" "build" "--jobs=8" "--compilation_mode=opt" "tensorflow:libtensorflow_c.so"

--- stderr
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Error: couldn't connect to server at '/home/tyoc213/.cache/bazel/_bazel_tyoc213/03736e16cd598f65b37ea03f9c7e8e67/server/server.socket' after 60 seconds.
thread 'main' panicked at 'failed to execute "bazel" "build" "--jobs=8" "--compilation_mode=opt" "tensorflow:libtensorflow_c.so"', /home/tyoc213/.cargo/registry/src/github.com-1ecc6299db9ec823/tensorflow-sys-0.5.0/build.rs:104
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

By the way, bash for windows is at https://msdn.microsoft.com/en-us/commandline/wsl/about and also reported a issue there https://github.com/Microsoft/BashOnWindows/issues/1467

**Comment by adamcrume** [comment]
It looks like TensorFlow doesn't support Windows until version 0.12: https://developers.googleblog.com/2016/11/tensorflow-0-12-adds-support-for-windows.html  Unfortunately, you can't install TensorFlow 0.12 and use it with the current Rust bindings (which use TensorFlow 0.10) because the TensorFlow C API (which we use under the hood) has been making breaking changes.  We'll catch up eventually, and then we'll take another look at this.

**Comment by tyoc213** [comment]
Tought... **bash** on windows is a *native ubuntu 14.04.4 LTS* (still under develpment `beta software`) is not run from a virtual machine but directly on Windows, because they implemented all the underlying things needed to run `UserMode Linux & its tools` on top of windows (as explained on the [video at 2:30 or 3:47](https://msdn.microsoft.com/en-us/commandline/wsl/about)), so I think that here we are not testing Windows support but more the shape of the actual implementation of this `UserMode Linux`.

**Comment by tyoc213** [comment]
A little update:


Well it is now updated to the latest, and also I uninstalled the 14.04 LTS and installed the xenial one which causes https//rustup.rs to fail still been able to install cargo and rust via `apt`, but now I get

```
$ RUST_BACKTRACE=1   cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.18
   Compiling num-traits v0.1.36
   Compiling pkg-config v0.3.8
   Compiling tensorflow-sys v0.5.0 (file:///mnt/c/Users/tyoc/test3/tensorflow-rust)
   Compiling num-complex v0.1.35
lsfailed to run custom build command for `tensorflow-sys v0.5.0 (file:///mnt/c/Users/tyoc/test3/tensorflow-rust)`
Process didn't exit successfully: `/mnt/c/Users/tyoc/test3/tensorflow-rust/target/debug/build/tensorflow-sys-ffa32813739b2107/build-script-build` (exit code: 101)
--- stdout
libtensorflow-sys/build.rs:31: output = "/mnt/c/Users/tyoc/test3/tensorflow-rust/target/debug/build/tensorflow-sys-ffa32813739b2107/out"
libtensorflow-sys/build.rs:33: source = "/mnt/c/Users/tyoc/test3/tensorflow-rust/tensorflow-sys/target/source-0.10.0"
libtensorflow-sys/build.rs:35: lib_dir = "/mnt/c/Users/tyoc/test3/tensorflow-rust/target/debug/build/tensorflow-sys-ffa32813739b2107/out/lib-0.10.0"
libtensorflow-sys/build.rs:39: Creating directory "/mnt/c/Users/tyoc/test3/tensorflow-rust/target/debug/build/tensorflow-sys-ffa32813739b2107/out/lib-0.10.0"
libtensorflow-sys/build.rs:43: library_path = "/mnt/c/Users/tyoc/test3/tensorflow-rust/target/debug/build/tensorflow-sys-ffa32813739b2107/out/lib-0.10.0/libtensorflow_c.so"
libtensorflow-sys/build.rs:48: target_path = "tensorflow/libtensorflow_c.so"
libtensorflow-sys/build.rs:102: Executing "git" "clone" "--branch=v0.10.0" "--recursive" "https://github.com/tensorflow/tensorflow.git" "/mnt/c/Users/tyoc/test3/tensorflow-rust/tensorflow-sys/target/source-0.10.0"
libtensorflow-sys/build.rs:106: Command "git" "clone" "--branch=v0.10.0" "--recursive" "https://github.com/tensorflow/tensorflow.git" "/mnt/c/Users/tyoc/test3/tensorflow-rust/tensorflow-sys/target/source-0.10.0" finished successfully
libtensorflow-sys/build.rs:77: Checking build file "/mnt/c/Users/tyoc/test3/tensorflow-rust/tensorflow-sys/target/source-0.10.0/tensorflow/BUILD"
libtensorflow-sys/build.rs:84: Patching build file "/mnt/c/Users/tyoc/test3/tensorflow-rust/tensorflow-sys/target/source-0.10.0/tensorflow/BUILD"

--- stderr
Clonar en «/mnt/c/Users/tyoc/test3/tensorflow-rust/tensorflow-sys/target/source-0.10.0»...
Note: checking out 'c715c3102df1556fc0ce88fc987440a3c80e5380'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Extrayendo archivos: 100% (4084/4084), done.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', src/libcore/result.rs:688
stack backtrace:
   1:     0x7f75fbc3fa30 - sys::backtrace::tracing::imp::write::h19a75f57079ca7d6Eju
   2:     0x7f75fbc44915 - panicking::default_handler::_<closure>::closure.42502
   3:     0x7f75fbc443bf - panicking::default_handler::heecbc8b8a021fa9bGwy
   4:     0x7f75fbc2e836 - sys_common::unwind::begin_unwind_inner::hd4253a1812044857bct
   5:     0x7f75fbc2efe8 - sys_common::unwind::begin_unwind_fmt::h281339998baa4cbdhbt
   6:     0x7f75fbc3f061 - rust_begin_unwind
   7:     0x7f75fbc71fdf - panicking::panic_fmt::h0d7335d3d6686f32zYL
   8:     0x7f75fbc13451 - result::Result<T, E>::unwrap::h9306331793537602264
                        at src/libcore/macros.rs:29
   9:     0x7f75fbc09a0a - main::hf3adb880ee36c6a4Kaa
                        at tensorflow-sys/build.rs:56
  10:     0x7f75fbc44044 - sys_common::unwind::try::try_fn::h16942181805834326396
  11:     0x7f75fbc3eff8 - __rust_try
  12:     0x7f75fbc43cd0 - rt::lang_start::hc0b5a65f976d4337Uoy
  13:     0x7f75fbc15329 - main
  14:     0x7f75fae0082f - __libc_start_main
  15:     0x7f75fbc083a8 - _start
  16:                0x0 - <unknown>
```

**Comment by adamcrume** [comment]
If TensorFlow doesn't build, then the Rust bindings won't build, and there's nothing I can do to change that.  I'm trying to catch up to TensorFlow 0.12, but that's still a work in progress.  You can try building TensorFlow 0.12 and file a bug against that project if it fails to build.

**Comment by sanmai-NL** [comment]
@tyoc213: have you tried with the latest versions of all software involved? Esp. [WSL](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/).

**Comment by bklooste** [comment]
I'm trying the latest , I got Bazel and tf to build  testing now .. will let you know .

**Comment by adamcrume** [comment]
Are there any problems still when building on Windows?  We've upgraded a through a few versions of TensorFlow, and some improvements have been made to the Windows build.

**Comment by adamcrume** [comment]
Closing due to lack of activity.
